# Generated by Django 2.1.7 on 2019-04-18 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('josusy_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user',
            new_name='username',
        ),
    ]
