# Generated by Django 2.1.7 on 2019-04-18 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('josusy_app', '0002_auto_20190418_0501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='email',
        ),
    ]
