# Generated by Django 2.1.7 on 2019-04-18 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('josusy_app', '0003_auto_20190418_0516'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Logger',
        ),
        migrations.DeleteModel(
            name='AccessRecord',
        ),
    ]
