# Generated by Django 2.2.1 on 2019-05-08 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('josusy_app', '0004_auto_20190418_0718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logger',
            old_name='email',
            new_name='user',
        ),
    ]
