# Generated by Django 2.1.7 on 2019-05-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('josusy_app', '0006_admins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admins',
            name='password',
            field=models.CharField(max_length=129),
        ),
        migrations.AlterField(
            model_name='logger',
            name='password',
            field=models.CharField(max_length=129),
        ),
    ]
