# Generated by Django 2.1.7 on 2019-05-20 05:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('josusy_app', '0007_auto_20190518_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='logger',
            name='lastlogin',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
