# Generated by Django 2.1.7 on 2019-05-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('josusy_app', '0008_logger_lastlogin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logger',
            name='lastlogin',
            field=models.DateTimeField(),
        ),
    ]
